name: Release
run-name: Publish release artifacts
on:
  release:
    types: [published]
jobs:
  generate-release-artifacts:
    name: Generate release artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Zip models
        run: ./make_release_artifacts.sh
      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: "*.zip"
