name: Validate config files

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1" # midnight every Monday

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Validate config.json
        run: find -name config.json|xargs check-jsonschema --schemafile https://raw.githubusercontent.com/imperialCHEPI/healthgps/main/schemas/v1/config.json
